### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Wgis** [robynetzan/velocity-persistent-server#1]
`[20:09:07 ERROR]: Couldn't pass DisconnectEvent to velocitypersistentserver
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:143) ~[?:?]
        at cool.rtz.velocitypersistentserver.PersistentServer.onDisconnect(PersistentServer.java:48) ~[?:?]
        at cool.rtz.velocitypersistentserver.Lmbda$21.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by robynetzan** [comment]
when did this error occur?

**Comment by Wgis** [comment]
After leave player

**Comment by Wgis** [comment]
After leave server from LimboAuth plugin. Need compatibility
